apiVersion: automation.cloudbees.io/v1alpha1
kind: CustomJob
name: edge job
description: Submit a job for execution by an edge runner

inputs:
  script:
    description: Script to execute.
    required: true
  labels:
    description: Comma-separated list of labels to select the desired edge runner
    required: true
    default: "self-hosted"
  disableTlsVerification:
    description: Disable TLS verification when communicating with the CloudBees API
    required: false
    default: "FALSE"
handlers:
  init:
    uses: docker://python:3-alpine
    command: sh
    args: |
      -c "echo 'Hello World!!'"
  callback:
    uses: docker://python:3-alpine
    command: python
    args: |
      -c "import os, json, sys;
      payload = json.loads(os.environ['PAYLOAD']);
      status = payload.get('status', 1);
      logs = payload.get('logs', '');
      print(f'Edge job completed with status: {status}');
      print(logs);
      sys.exit(status)"
    env:
      PAYLOAD: ${{ handler.payload }}
