apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  # push:
  #   branches:
  #     - '**'
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: "DEV"

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world - ${{ vars.vars_1 }}"
  
  my-edge-job:
    with:
      script: |
        echo "Hello world! I'm $(whoami) on $(hostname)"

        echo "\033[0;31m Inputs context \033[0m"
        echo "${{ toJSON(inputs) }}"

        echo "\033[0;31m Vars context \033[0m"
        echo "${{ vars.vars_1 }}"

        echo "\033[0;31m CloudBees context \033[0m"
        echo "${{ toJSON(cloudbees) }}"

      labels: "pinaki-local"
    delegates: ./edge-custom-job.yaml

  test:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world - duplicate - test preprod-5"
          echo "testing concurrency with postgres - test 2"
  deploy:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world - duplicate - deploy - 1"

  mask:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo -n "hello" | cloudbees mask
          echo "hello world"
